### ISSUE TITLE
Blogpost links to invalid url

### ISSUE THREAD

**Issue by JordanSussman** [jfrog/kubexray#18]
Hello,

Currently, the [blogpost](https://jfrog.com/blog/jfrog-kubexray-extends-deep-scanning-security-to-kubernetes-runtime/) announcing this project links to https://github.com/jfrog/kubexray/Read.me instead of https://github.com/jfrog/kubexray/blob/master/README.md, the specific section with the incorrect url is in the 5th paragraph from the bottom.

**Comment by ankushchadha** [comment]
This issue has been fixed. Thanks, @JordanSussman for reporting it.
